'use client';
import {useState,useEffect,useRef} from 'react';
import type {Brand} from '../../lib/brands';
const statuses=['In Market','Incubation','Acquired'];
const fresh:Brand={id:'',name:'',category:'',status:'Incubation',website:'',image:'',description:'',visible:0,position:0,revision:1};
export default function Manager(){
 const [brands,setBrands]=useState<Brand[]>([]),[draft,setDraft]=useState<Brand|null>(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);const formRef=useRef<HTMLFormElement>(null);
 async function load(){setLoading(true);try{const r=await fetch('/api/brands?all=1');const x:any=await r.json();if(!r.ok)throw new Error(x.error);setBrands(x);}catch(e){setError(e instanceof Error?e.message:'Could not load brands.');}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 function edit(b:Brand){if(draft&&!confirm('Discard your unsaved edits?'))return;setDraft({...b});setError('');setNotice('');requestAnimationFrame(()=>formRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));}
 function change(key:keyof Brand,value:string|number){setDraft(d=>d?{...d,[key]:value}:null);}
 async function save(e:React.FormEvent){e.preventDefault();if(!draft)return;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/brands',{method:draft.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const result:any=await r.json();if(!r.ok)throw new Error(result.error);setNotice(`${draft.name} saved. ${draft.visible?'Your site is up to date.':'This brand is hidden from the site.'}`);setDraft(null);await load();}catch(e){setError(e instanceof Error?e.message:'Could not save. Your edits are still here.');}finally{setBusy(false);}}
 async function upload(file:File|undefined){if(!file)return;setUploading(true);setError('');try{if(file.size>5*1024*1024)throw new Error('Choose an image smaller than 5 MB.');const r=await fetch('/api/upload',{method:'POST',headers:{'Content-Type':file.type},body:file});const x:any=await r.json();if(!r.ok)throw new Error(x.error);change('image',x.url);}catch(e){setError(e instanceof Error?e.message:'Upload failed.');}finally{setUploading(false);}}
 useEffect(()=>{if(!draft)return;const fn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[draft]);
 useEffect(()=>{const mc=(navigator as any).modelContext;if(!mc?.registerTool)return;mc.registerTool({name:'list_brands',description:'Read the saved brand portfolio including hidden brands and current statuses.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>({content:[{type:'text',text:JSON.stringify(brands)}]})});mc.registerTool({name:'prepare_brand_editor',description:'Open an existing brand or a new brand draft in the editor. Does not save changes.',inputSchema:{type:'object',properties:{id:{type:'string'}},additionalProperties:false},execute:async({id}:{id?:string})=>{if(draft)return {content:[{type:'text',text:'An unsaved draft is open. Save or cancel it first.'}]};const b=id?brands.find(b=>b.id===id):{...fresh,position:brands.length};if(!b)return {content:[{type:'text',text:'Brand not found.'}]};edit(b);return {content:[{type:'text',text:'Brand editor opened. Review and save using the form.'}]};}});return()=>{mc.unregisterTool('list_brands');mc.unregisterTool('prepare_brand_editor');};},[brands,draft]);
 return <div className="admin"><header className="admin-header"><a className="wordmark" href="/"><img src="/idb-logo-white.png" alt="Impact Driven Brands"/></a><a href="/" target="_blank" rel="noreferrer">View site</a></header><main className="admin-body"><div className="admin-heading"><div><p className="eyebrow">PORTFOLIO EDITOR</p><h1>Manage your brands.</h1><p>Keep your portfolio current, all in one place.</p></div><button className="btn primary" disabled={loading||busy||uploading} onClick={()=>edit({...fresh,position:brands.length?Math.max(...brands.map(b=>b.position))+1:0})}>+ Add brand</button></div>
 {notice&&<p className="notice" role="status">{notice}</p>}{error&&<p className="notice error" role="alert">{error}</p>}
 {loading?<p role="status">Loading brands…</p>:<div className="admin-list">{brands.length===0?<p>No brands yet. Add your first brand to get started.</p>:brands.map(b=><div className="admin-row" key={b.id}><img src={b.image||'/favicon.svg'} alt=""/><div className="row-info"><strong>{b.name}</strong><p>{b.category} · Order {b.position+1}{!b.visible&&<span className="hidden-label">Hidden</span>}</p></div><span className="row-status">{b.status}</span><button className="btn" disabled={busy||uploading} aria-label={`Edit ${b.name}`} onClick={()=>edit(b)}>Edit brand</button></div>)}</div>}
 {draft&&<form ref={formRef} className="editor edit-target" onSubmit={save}><h2>{draft.id?`Edit ${draft.name}`:'Add a new brand'}</h2><fieldset disabled={busy||uploading} style={{border:0,padding:0,margin:0}}><div className="form-grid"><label className="field">Brand name<input required autoFocus maxLength={100} value={draft.name} onChange={e=>change('name',e.target.value)}/></label><label className="field">Category<input required maxLength={70} placeholder="e.g. Personal Care" value={draft.category} onChange={e=>change('category',e.target.value)} list="categories"/><datalist id="categories"><option>Personal Care</option><option>Food</option><option>Baby</option></datalist></label><label className="field">Status<select value={draft.status} onChange={e=>change('status',e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="field">Display order<input type="number" required min="1" max="100001" value={draft.position+1} onChange={e=>change('position',Number(e.target.value)-1)}/><small>Lower numbers appear first.</small></label><label className="field span2">Brand website<input type="url" placeholder="https://…" maxLength={2000} value={draft.website} onChange={e=>change('website',e.target.value)}/></label><label className="field span2">Short description (optional)<textarea maxLength={500} value={draft.description} onChange={e=>change('description',e.target.value)}/></label><div className="field span2">Brand image{draft.image&&<img className="editor-preview" src={draft.image} alt="Brand image preview"/>}<label className="upload">Upload a photo<input aria-label="Upload brand image" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload(e.target.files?.[0])}/><small>JPG, PNG, or WebP · Up to 5 MB · Landscape works best</small></label><label className="field">Or use an image address<input type="text" maxLength={2000} placeholder="https://…" value={draft.image} onChange={e=>change('image',e.target.value)}/></label></div><label className="check span2"><input type="checkbox" checked={!!draft.visible} onChange={e=>change('visible',e.target.checked?1:0)}/>Feature this brand on the website</label></div><div className="form-actions"><button className="btn primary" type="submit">{busy?'Saving…':uploading?'Uploading…':'Save brand'}</button><button className="btn" type="button" onClick={()=>{if(confirm('Discard your unsaved edits?'))setDraft(null);}}>Cancel</button></div></fieldset></form>}
 <p className="admin-footnote">Saved changes appear on the website immediately. Uncheck “Feature this brand” to hide it while keeping its details.</p></main></div>;
}
