'use client';
import {useState} from 'react';
import type {Brand} from '../lib/brands';
export function Wordmark(){return <a className="wordmark" href="/" aria-label="Impact Driven Brands home"><img src="/idb-logo-white.png" alt="Impact Driven Brands"/></a>;}
export default function Portfolio({brands,unavailable=false}:{brands:Brand[];unavailable?:boolean}){
 const [filter,setFilter]=useState('All brands');const visible=brands.filter(b=>filter==='All brands'||b.status===filter);
 return <><header className="nav wrap"><Wordmark/><nav><a href="#brands">Our brands</a><a href="#about">Our purpose</a><a className="nav-contact" href="mailto:hello@impactdrivenbrands.com">Let’s talk</a></nav></header>
 <main><section className="hero wrap"><div className="eyebrow">INDEPENDENT THINKING. EVERYDAY IMPACT.</div><h1>Good brands.<br/><span>Greater impact.</span></h1><div className="hero-bottom"><p>We build consumer brands with a purpose.<br/>From a bold idea to an everyday essential.</p><a href="#brands" className="pill monochrome">Meet our brands</a></div><div className="hero-rule"><span>CPG INCUBATOR</span><span>RETAIL + ECOMMERCE</span><span>BUILT WITH PURPOSE</span></div></section>
 <section id="brands" className="portfolio wrap"><div className="section-top"><div><p className="eyebrow">THE PORTFOLIO</p><h2>Different brands.<br/>Shared ambition.</h2></div><p>Products people love.<br/>Purpose that goes further.</p></div><div className="filter-bar" aria-label="Filter brands">{['All brands','In Market','Incubation','Acquired'].map(s=><button key={s} aria-pressed={filter===s} onClick={()=>setFilter(s)}>{s}<span>{s==='All brands'?brands.length:brands.filter(b=>b.status===s).length}</span></button>)}</div>
 {unavailable?<div className="empty" role="alert">Our portfolio is temporarily unavailable. <button onClick={()=>location.reload()}>Try again</button></div>:visible.length===0?<div className="empty">No brands in this stage yet.</div>:<div className="brand-grid">{visible.map((b,i)=><article className="brand-card" key={b.id}><a className="brand-image" href={b.website||undefined} target="_blank" rel="noreferrer" aria-label={`Visit ${b.name}`}><img src={b.image||'/favicon.svg'} alt={`${b.name} products`} loading={i<2?'eager':'lazy'} onError={e=>{e.currentTarget.src='/favicon.svg';e.currentTarget.classList.add('fallback');}}/><span className={'status '+b.status.toLowerCase().replace(' ','-')}>{b.status}</span><span className="visit">Explore brand</span></a><div className="brand-info"><h3>{b.name}</h3><span>{b.category}</span></div>{b.description&&<p className="brand-description">{b.description}</p>}</article>)}</div>}</section>
 <section id="about" className="purpose"><div className="wrap purpose-grid"><p className="eyebrow">WHY WE EXIST</p><div><h2>Everyday products.<br/>Extraordinary potential.</h2><p>Impact Driven Brands is a CPG incubator bringing innovative, social mission brands to retail and eCommerce. We believe the things people buy every day can help move the world forward.</p><a className="text-link" href="mailto:hello@impactdrivenbrands.com">Build something meaningful with us</a></div></div></section>
 <section className="contact wrap"><p className="eyebrow">GREAT THINGS START WITH A CONVERSATION</p><h2>Let’s make<br/><span>an impact.</span></h2><a href="mailto:hello@impactdrivenbrands.com">hello@impactdrivenbrands.com</a></section></main>
 <footer className="wrap"><Wordmark/><div>© {new Date().getFullYear()} Impact Driven Brands</div><a href="/admin">Manage brands</a></footer></>;
}
